sonar.projectKey=aggy296_Web-App
sonar.organization=aggy296

sonar.sources=oders-api
sonar.tests=oders-api/tests

sonar.test.inclusions=oders-api/tests/**/*.js
sonar.exclusions=oders-api/tests/**/*.js

sonar.sourceEncoding=UTF-8
