apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: qa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: web-app

  template:
    metadata:
      labels:
        app: web-app

    spec:
      containers:
      - name: web-app

        image: ghcr.io/aggy296/web-app:468db28a50a34a0a4b030866a972417c23ddee6b

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"

        env:
        - name: OTEL_SERVICE_NAME
          value: web-app

        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://splunk-otel-collector-agent.observability.svc.cluster.local:4318

        - name: OTEL_RESOURCE_ATTRIBUTES
          value: deployment.environment=qa    

        envFrom:
        - configMapRef:
            name: web-app-config

        - secretRef:
            name: web-app-secret